### ISSUE TITLE
`rust` branch tracking issue

### ISSUE THREAD

**Issue by wincent** [wincent/docvim#43]
Just some known things I want to get to:

- [ ] Implement histogram diff.
- [ ] Implement optimizations for Myers diff (it's still used as a fallback for the histogram diff, so should be fast).
- [ ] Improve snapshot diff output (for example, not currently printing hunk headers or limiting context lines).
- [ ] Finish Lua parser.
- [ ] Make Vimscript lexer + parser.
- [ ] Make output pretty-printer.
- [ ] Implement benchmarks.
- [ ] Clean up tire-fire that is the `RingBuffer` implementation.
